using System;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.Linq;

namespace AdventCs
{
	public class AdventDay3
	{

		public  record Coordinate
		{
			public int x { get; init; }
			public int y { get; init; }
		}
		
		public static bool[][] TreePattern =
		{
new[]{false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,true,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,true,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,true},
new[]{false,false,true,false,false,false,false,false,false,true,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,true,false,false,true,false,false,false,false,false,false,false},
new[]{false,true,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,true,true,false,false,true,false,true,true,false,false,false,false,true,false},
new[]{false,false,true,false,false,false,false,true,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{true,true,false,false,false,false,false,false,false,false,false,false,true,false,true,true,false,false,false,true,false,false,false,false,true,true,false,false,true,false,false},
new[]{false,false,false,true,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true},
new[]{false,false,true,true,false,true,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false},
new[]{false,false,false,true,false,true,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,true,true,false,true,false},
new[]{false,true,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false},
new[]{false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,true,false,false,false,false,false,false,false,true,false},
new[]{false,false,false,false,false,false,true,false,false,false,true,false,false,false,true,false,true,true,false,false,false,false,false,false,false,true,false,true,false,false,false},
new[]{false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,true,false,false,false,true,true,false,false,false,false,false,false,false,false,false},
new[]{true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,true,false,false,false,false,false,false,false,true},
new[]{false,false,true,false,false,true,false,false,true,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false},
new[]{true,true,false,false,false,false,false,false,true,false,false,false,true,false,false,true,false,true,true,false,false,false,false,false,false,false,true,false,false,false,false},
new[]{false,false,true,false,true,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,true},
new[]{true,false,false,true,false,false,true,true,false,false,false,false,false,false,true,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false},
new[]{false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,true,false,true,false,false,false,true,false,false,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false},
new[]{false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,true,true,true,false,false,false,false,true,false,false},
new[]{false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false},
new[]{true,false,false,false,false,true,false,false,true,true,true,true,false,false,false,false,true,false,false,false,false,false,true,false,false,true,false,false,false,false,true},
new[]{false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,true,false,false},
new[]{false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,true,false,false,true,true,true,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,true,false,false,true,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false},
new[]{false,false,false,true,false,true,false,true,false,true,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false},
new[]{true,false,false,false,false,true,true,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,true,true,false,false,false,false,false},
new[]{true,false,false,true,false,false,false,false,false,false,false,true,false,false,true,false,false,true,false,false,true,false,false,false,true,true,false,false,false,false,false},
new[]{true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false},
new[]{false,true,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,true,false,false,false,false,false,false,false,false,true},
new[]{false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,true,false,false,false,true,false,true,false,false},
new[]{false,false,false,false,false,true,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false},
new[]{false,false,true,false,true,true,false,false,true,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,true,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false},
new[]{false,true,false,false,false,false,false,true,false,false,true,false,false,false,false,true,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false},
new[]{false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,true,false,false,false,true,false,false,false},
new[]{false,true,true,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,true,true,false,true,false,false,false,false,true,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false},
new[]{false,false,false,false,false,false,true,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false},
new[]{true,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,true,false,false,true,false,false,false,true,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,true,false,false,false,false,false,false,true,false,false},
new[]{false,false,false,false,false,false,false,false,true,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true},
new[]{false,false,false,false,false,false,false,true,false,false,false,true,false,false,true,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,true,false,false,true,false,false,false,true,true,false,false,false,true,false,false,true,false,true,false,false,false,false,false,true,false,false,false,true,false},
new[]{false,true,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,true,true,true,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,true,false,true,false,false,false,true,false,false,true,true,false,false,true,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false},
new[]{true,false,false,true,false,false,true,false,false,false,false,false,true,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false},
new[]{false,false,true,true,false,false,false,false,false,true,true,false,false,false,true,false,false,false,false,false,false,true,false,false,true,true,false,false,false,false,false},
new[]{true,false,false,false,false,false,true,false,false,false,false,false,true,true,true,false,true,false,false,false,false,false,true,false,false,false,false,true,true,false,false},
new[]{false,true,false,false,false,false,false,false,false,false,false,false,false,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,true,false,true,false,false,false,true,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,true,false,true,false,false,false,false,false,false},
new[]{false,true,false,true,false,true,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,true,false,true,false},
new[]{true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,true,true,false,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true},
new[]{false,false,false,false,false,false,false,false,false,false,true,false,false,true,true,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,true,true,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false},
new[]{true,false,false,false,false,false,false,false,false,false,true,false,true,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false},
new[]{false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false},
new[]{false,true,false,false,true,false,false,true,true,false,false,false,true,false,true,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false},
new[]{false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,true},
new[]{false,false,false,false,false,false,false,false,true,false,false,false,false,true,true,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,true,false,false,false,false},
new[]{true,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,true,false,true,false,false,false,false,true,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,true,true,false,true,false,false,false,false,false,true,false,false,true,false,false,false,false,false,true,false,true,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,true,false,true},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,true,false,false,false,true,false,false,false,true,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false},
new[]{false,false,false,true,false,false,true,false,false,true,false,true,false,false,true,true,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false},
new[]{false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,true,false,true},
new[]{false,false,false,false,false,false,true,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,true,true,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,true,false,false,false,true},
new[]{false,false,false,true,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,true,true,false,false,false,false,true,false,true,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false},
new[]{false,true,false,false,false,false,false,false,true,false,true,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,true,false,false,true,false,true,true,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,true},
new[]{false,false,false,true,false,false,false,false,true,false,true,false,false,false,true,false,false,true,false,false,false,false,false,false,false,true,false,false,true,false,false},
new[]{false,false,true,false,false,false,true,true,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,true,false,false,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false},
new[]{false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false},
new[]{false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,true},
new[]{false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false},
new[]{false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,true,true,false,false,true,true,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,true,false,false,true,false,true,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false},
new[]{false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,true,true,false,false,false,false,true,false,true,false,false},
new[]{false,true,false,false,false,true,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,true,true,true,false,false},
new[]{true,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true},
new[]{false,false,false,false,true,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,true,true,false,false},
new[]{true,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,true,false,false,false,false,true},
new[]{false,false,true,false,false,true,true,false,false,true,false,false,false,false,false,false,false,true,false,false,true,false,true,false,false,false,false,false,false,true,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,true},
new[]{false,true,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,true,false,false,false,false,false,false,false,false},
new[]{false,true,false,false,false,false,true,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false},
new[]{false,false,false,true,false,true,false,false,true,false,false,true,false,false,true,false,false,false,false,true,false,false,false,false,false,true,false,false,true,false,false},
new[]{false,false,false,false,true,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false},
new[]{true,false,false,false,false,false,false,false,false,false,false,true,true,true,false,false,false,false,false,false,true,true,true,false,false,false,false,false,false,false,false},
new[]{false,true,true,false,true,true,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false},
new[]{false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false},
new[]{true,false,true,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,true,false},
new[]{false,false,false,false,false,false,false,true,true,true,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,true,true,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false},
new[]{false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false},
new[]{false,false,false,true,false,false,false,false,false,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,true,true,false,false,false},
new[]{false,false,false,false,true,true,false,false,true,true,false,false,false,true,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false},
new[]{false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,true,false,false,true,false,false,false,false,false,true,false,false,true,false},
new[]{false,false,false,false,false,false,false,false,false,false,true,true,true,true,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,true},
new[]{false,true,true,false,false,false,false,true,false,false,true,false,true,false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false},
new[]{false,false,false,true,false,true,false,true,true,false,true,false,true,false,false,false,true,false,false,false,false,true,false,true,false,true,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,false,true,true,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,true},
new[]{false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,true,true,false,true},
new[]{true,true,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false},
new[]{false,true,false,false,false,true,false,false,false,false,false,true,false,false,false,false,true,false,true,false,false,true,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false},
new[]{false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,true,true},
new[]{false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,true,false,false,false,false,false,false,false,false},
new[]{true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,true,true,false,true,false},
new[]{false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false},
new[]{true,false,false,true,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,true,false,false,false,true,false,false,true,false,false,true,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,true},
new[]{false,false,false,true,false,true,false,false,false,false,false,false,false,true,false,false,false,true,false,true,true,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,true,false,true,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,true,false,false,false,false,false},
new[]{true,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,true,false,false,false,true,false},
new[]{true,true,true,false,false,true,false,false,false,false,true,true,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,true,false,false},
new[]{false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,true,false,false},
new[]{false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false},
new[]{false,false,true,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,true,false,false,false,true,false,false,false,false,false,false,false,true,false,true,true,false,false,false,true,false,true,false,false,false,false,false,false,false,true},
new[]{false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true},
new[]{false,false,false,false,true,false,true,false,false,false,true,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false},
new[]{false,true,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{true,false,false,false,false,false,false,false,true,false,false,false,true,true,true,false,false,false,false,false,true,false,true,false,true,false,false,true,false,false,false},
new[]{true,false,false,false,false,true,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false},
new[]{false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false},
new[]{false,false,false,false,false,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false},
new[]{false,true,true,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,true,true,false,true,false},
new[]{true,false,false,false,false,false,false,true,true,false,false,true,true,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,true},
new[]{false,true,true,false,false,false,false,false,false,false,true,true,false,true,true,false,false,false,true,false,true,true,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false},
new[]{false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,true,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false},
new[]{true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,true,true,false,true,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,true,false,true,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false},
new[]{false,true,false,false,true,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false},
new[]{false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,true,false,false,false,true,true,false,false},
new[]{false,false,true,false,false,true,false,true,false,false,false,false,false,true,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false},
new[]{true,false,false,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false},
new[]{true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,true,false,false,false,false,false,false,true},
new[]{false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,true,false,false,false,false,true,false,true,false,false,false,true,false,true},
new[]{false,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,true},
new[]{true,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,true,false},
new[]{false,false,false,false,true,true,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,true,false,false,false,false,true,true,false,false},
new[]{false,true,false,false,false,true,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false},
new[]{false,false,true,false,false,false,false,false,false,false,false,false,false,true,true,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false},
new[]{true,false,false,false,false,true,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false},
new[]{true,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false},
new[]{false,true,false,false,false,true,false,false,false,false,false,false,false,true,false,false,true,false,false,false,true,false,true,false,false,false,true,false,false,true,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,true,false,false,false,false,false,true,false,false,false,false,false},
new[]{true,true,true,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,true,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false},
new[]{false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,true,false,false},
new[]{false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true},
new[]{true,false,false,false,false,false,true,false,true,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,true,false,false,true,false,false,false,false,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,true,true,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,true,false,false,false,false,false,false},
new[]{false,true,true,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,true,true,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false},
new[]{false,false,true,true,true,false,false,false,false,false,false,false,true,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,true},
new[]{false,true,false,false,false,false,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,false,false},
new[]{false,false,false,false,false,false,true,false,false,false,true,false,false,true,false,false,true,false,false,true,false,false,true,false,false,false,false,false,false,false,true},
new[]{false,false,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,true,false,false,true,false,false,true,false,false,true,false,false,false,true},
new[]{false,false,false,false,false,true,true,false,false,false,true,false,true,true,false,false,false,false,true,false,true,false,false,false,true,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false},
new[]{false,true,true,false,false,true,true,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,true,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,true,false,false,false,true,false,true,false,false,false,true,false,false,false,false,false},
new[]{true,false,true,true,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true},
new[]{false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,true,false,false,false,true,true,false,false,false,false,false,false,false,true},
new[]{false,false,true,false,true,true,false,false,false,false,false,false,false,false,true,true,true,false,false,true,false,false,false,false,false,false,true,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,true,true,false,false,false,false,false,false,true,false,false,true,false,false,true},
new[]{false,true,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false},
new[]{true,true,false,false,false,false,false,false,false,true,true,false,true,true,false,true,true,false,false,false,false,false,false,true,true,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,true,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,true,true,true},
new[]{false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,true,true,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false},
new[]{true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,true,false,true,false,false,true,false,false,false},
new[]{false,false,true,false,true,false,false,false,false,false,true,false,false,true,false,true,true,false,false,false,false,false,true,true,false,false,false,true,false,false,false},
new[]{false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false},
new[]{true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false},
new[]{false,true,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,true,true,false,true,true,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,true,true,false,true,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,false,false,true,true,false,false,false,false,false},
new[]{false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,false,false,false,false,false,false,false,false},
new[]{false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,true,false,false,false,true,false,false,false,true,false,true},
new[]{false,false,true,false,true,false,false,false,false,false,false,true,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true},
new[]{true,false,true,false,false,true,false,false,true,true,false,false,false,false,false,false,false,false,false,true,false,true,false,true,false,false,false,true,false,false,false},
new[]{false,false,false,false,true,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,true,false,false,true},
new[]{false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,true,true,false,false,false,false,true,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,true,true,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true},
new[]{true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false},
new[]{true,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,true,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false},
new[]{false,false,true,false,true,false,true,true,false,false,true,false,true,false,false,false,true,true,false,false,false,false,false,false,false,false,true,false,true,true,false},
new[]{false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,true,true,true,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,true,true,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false},
new[]{true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false},
new[]{false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,true,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,true},
new[]{true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,true,true,true,false,false,false,false,false,true,false,false,false},
new[]{false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,true,false,true,false},
new[]{false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,true,true,false,false,true},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,true,false,false,false,false,false,true,false,false,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false},
new[]{false,true,false,false,false,true,false,false,false,false,false,false,true,false,true,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,true},
new[]{false,false,false,false,false,false,true,false,true,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,true,false,false,true,true,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{true,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,true,false,false,false,true,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,false,false,false,true,true,false,false},
new[]{false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true},
new[]{true,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,true,true,true,false,false,false,false,true,false,true,false,true,true,false,true,false,false,false,false},
new[]{false,false,true,false,false,false,true,false,true,true,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,true,false,false,false,false,true,true,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,false,false,true,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,true},
new[]{false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false},
new[]{true,false,true,false,false,false,false,false,false,false,false,true,true,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,true,true,false},
new[]{false,true,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,true,false,false,true,false,false,false,true,true},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false},
new[]{false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,true,false,true,false,false,false,true,false,true,false,false,true,false,false,false},
new[]{false,false,false,false,false,true,false,false,true,true,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{true,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false},
new[]{true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,true,false,false,false},
new[]{false,false,true,true,false,false,false,false,false,false,false,false,true,false,true,false,false,false,true,false,false,false,true,false,false,false,false,false,false,true,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,true,false,true,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,true,true,true,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,true,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,true,false},
new[]{false,false,false,false,false,false,false,true,true,false,false,true,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false},
new[]{false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,true,true,false,false,false,false},
new[]{false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false},
new[]{false,false,false,true,false,true,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,true,false,false,true,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,true,true,true,false,false,true,false},
new[]{true,false,true,false,false,false,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,true,true,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,true,true,false,true,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,true,true,false,false,false,true,false,false},
new[]{false,true,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,true,false,true,false,true,false,false,false,true,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false},
new[]{true,true,false,false,false,false,false,false,false,false,true,true,false,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,true,false,false,true,false,false,false,true,false,true,true,false,false,false,false},
new[]{true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,true,false,false,true,false,false,true,false,false,true,false,false,false},
new[]{false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,true,false,false,false,false,true,false,false,false,false,false,false,false,true},
new[]{false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,true,false,false,true,false,false,true,true,false,false,true,false,false,false,false,false},
new[]{false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false},
new[]{false,false,false,true,true,true,false,false,false,true,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,true,false,false,false,false,false,true,true,true,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,true,false,false,false,false},
new[]{true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false},
new[]{false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,true,true,false,false,false,false,false,false,false,true,false,false,true,true,false,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,true,false,false,true,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false},
new[]{false,false,false,true,false,false,false,false,true,true,false,true,false,false,false,true,false,false,true,false,true,false,false,false,true,false,false,false,false,true,false},
new[]{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,true,false,true,true},
new[]{false,false,false,false,false,false,true,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false},
new[]{false,false,false,false,false,false,true,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,true,true,false,false,false,false,false,false},
new[]{true,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,true,false,true,true,false,false},
		};
		
		public static Coordinate GetNextPosition(Coordinate currentPosition, Coordinate movement)
		{
			return currentPosition with {
				x = currentPosition.x + movement.x,
				y = currentPosition.y + movement.y
				};
		}
		
		public static bool CheckTreeAtPosition(int x , bool[] trees)
		{
			return trees[(x % trees.Length)];
		}

		public static int CheckTreesPassed(bool[][] treesPattern, Coordinate start, Coordinate movement)
		{
			return treesPattern
				.Where((x,i)=> i% movement.y ==0)
				.Select((x,j) => 
				CheckTreeAtPosition( movement.x*j , x)
			).Count(x => x);
		}

		public static Coordinate[] slopes =
		{
			new() {x = 1, y = 1},
			new() {x = 3, y = 1},
			new() {x = 5, y = 1},
			new() {x = 7, y = 1},
			new() {x = 1, y = 2},
		};
		
		public static int CheckTreesPassedMultipleSlopes(bool[][] treesPattern, Coordinate start, List<Coordinate> movement)
		{

		return movement.Select(slope =>
				treesPattern
					.Where((x, i) => i % slope.y == 0)
					.Select((x, j) =>
						CheckTreeAtPosition(slope.x * j, x)
					).Count(x => x)
			)
				.Aggregate(1, (x,y) => x * y);
		}
	}
}