name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_tag:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: My Script
      run: bash .github/listAdvent.sh
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "AdventCs/Advent.cs"
        token: ${{secrets.GITHUB_TOKEN}}
